name       : libplacebo
version    : 5.264.1
release    : 18
source     :
    - https://code.videolan.org/videolan/libplacebo/-/archive/v5.264.1/libplacebo-v5.264.1.tar.bz2 : 99ebcf90f3d3c6c4e5b9364091575b9b75d5a1a7d2356a60d8cf67d4fd93b5da
license    : LGPL-2.1-or-later
component  : multimedia.library
summary    : Reusable library for GPU-accelerated image/video processing primitives and shaders, as well a batteries-included, extensible, high-quality rendering pipeline (similar to mpv's vo_gpu). Supports Vulkan and OpenGL.
description: |
    libplacebo is, in a nutshell, the core rendering algorithms and ideas of mpv rewritten as an independent library. As of today, libplacebo contains a large assortment of video processing shaders, focusing on both quality and performance.
builddeps  :
    - pkgconfig(dovi)
    - pkgconfig(lcms2)
    - pkgconfig(libunwind)
    - pkgconfig(shaderc)
    - pkgconfig(spirv-cross-c-shared)
    - pkgconfig(vulkan)
    - python-glad2
    - python-jinja
    - vulkan-headers
setup      : |
    %meson_configure -Ddemos=false
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
