name       : libplacebo
version    : 1.21.0
release    : 1
source     :
    - https://code.videolan.org/videolan/libplacebo/-/archive/v1.21.0/libplacebo-v1.21.0.tar.gz : 19e58f0a3c09f67680aa56263ef28ee1a1f458123872fce91b1fb7f4271b5496
license    : LGPL-2.1-or-later
component  : multimedia.library
summary    : Reusable library for GPU-accelerated video/image rendering primitives, as well as a standalone Vulkan-based image/video renderer.
description: |
    libplacebo is essentially the core rendering algorithms and ideas of mpv turned into a library.
builddeps  :
    - pkgconfig(lcms2)
    - pkgconfig(vulkan)
    - glslang-devel
    - vulkan-headers
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
