name       : libplacebo
version    : 4.208.0
release    : 15
source     :
    - https://code.videolan.org/videolan/libplacebo/-/archive/v4.208.0/libplacebo-v4.208.0.tar.bz2 : c89a80655ab375e4809415bb597c638607fc150fa6f6bb830dd502fec7f0ba95
license    : LGPL-2.1-or-later
component  : multimedia.library
summary    : Reusable library for GPU-accelerated image/video processing primitives and shaders, as well a batteries-included, extensible, high-quality rendering pipeline (similar to mpv's vo_gpu). Supports Vulkan and OpenGL.
description: |
    libplacebo is, in a nutshell, the core rendering algorithms and ideas of mpv rewritten as an independent library. As of today, libplacebo contains a large assortment of video processing shaders, focusing on both quality and performance.
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(lcms2)
    - pkgconfig(libunwind)
    - pkgconfig(shaderc)
    - pkgconfig(spirv-cross-c-shared)
    - pkgconfig(vulkan)
    - pkgconfig(x11)
    - mako
    - vulkan-headers
setup      : |
    %meson_configure -Ddemos=false
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
