name       : libplacebo
version    : 2.72.2
release    : 7
source     :
    - https://code.videolan.org/videolan/libplacebo/-/archive/v2.72.2/libplacebo-v2.72.2.tar.bz2 : a308b16404d1db0c641a698a0f37d92d7b96a794e32f44e1d2d0f6cec66b1995
license    : LGPL-2.1-or-later
component  : multimedia.library
summary    : Reusable library for GPU-accelerated image/video processing primitives and shaders, as well a batteries-included, extensible, high-quality rendering pipeline (similar to mpv's vo_gpu). Supports Vulkan and OpenGL.
description: |
    libplacebo is essentially the core rendering algorithms and ideas of mpv turned into a library. This grew out of an interest to accomplish the following goals:
    - Clean up mpv's internal RA API and make it reusable for other projects.
    - Provide a standard library of useful GPU-accelerated image processing primitives based on GLSL.
    - Rewrite core parts of mpv's GPU-accelerated video renderer on top of redesigned abstractions.
builddeps  :
    - pkgconfig(SPIRV-Tools)
    - pkgconfig(epoxy)
    - pkgconfig(lcms2)
    - pkgconfig(vulkan)
    - glslang-devel
    - mako
    - vulkan-headers
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
