name       : libplacebo
version    : 2.43.0
release    : 4
source     :
    - https://code.videolan.org/videolan/libplacebo/-/archive/v2.43.0/libplacebo-v2.43.0.tar.gz : 80c497a983067f00761da395798da603b3efd2d833992bf59d32d6068aabfcc4
license    : LGPL-2.1-or-later
component  : multimedia.library
summary    : Reusable library for GPU-accelerated video/image rendering primitives, as well as a standalone Vulkan-based image/video renderer.
description: |
    libplacebo is essentially the core rendering algorithms and ideas of mpv turned into a library.
builddeps  :
    - pkgconfig(SPIRV-Tools)
    - pkgconfig(epoxy)
    - pkgconfig(lcms2)
    - pkgconfig(vulkan)
    - glslang-devel
    - vulkan-headers
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check